create TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT,
    following_id BIGINT,
    created TIMESTAMP WITHOUT TIME ZONE,
    UNIQUE(follower_id, following_id)
);